use_frameworks!

target 'TCTimePicker_Example' do
  pod 'TCTimePicker', :path => '../'

  target 'TCTimePicker_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
